packages:
  - .

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@swc/core'
  - bufferutil
  - core-js
  - esbuild
  - protobufjs
  - sharp
  - utf-8-validate
  - workerd
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
