'use client'

import { useState } from 'react'
import { DateRange } from 'react-day-picker'
import { format, addDays } from 'date-fns'
import {
  Save,
  CalendarDays,
  ChevronLeft,
  ChevronRight,
  Check,
} from 'lucide-react'
import { SubmitHandler, useForm } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup'
import * as yup from 'yup'

import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Checkbox } from '@/components/ui/checkbox'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { DatePicker, DatePickerWithRange } from '@/components/ui/date-picker'

interface SavePlanModalProps {
  isOpen: boolean
  onClose: () => void
  onSave: (name: string, dateInput: Date | DateRange) => Promise<void>
  isSaving?: boolean
  mode?: 'WEEK' | 'DAY_FULL' | 'DAY_BREAKFAST' | 'DAY_LUNCH' | 'DAY_DINNER'
  selectedDay?: string | null
  mealPlanTitle?: string
}

const schema = yup.object().shape({
  planName: yup.string().required('Please enter a plan name'),
  dateInput: yup
    .mixed<Date | DateRange>()
    .test('has-date', 'Please select schedule day(s)', (value) => {
      if (!value) return false
      if (value instanceof Date) return true
      return [value.from, value.to].every((date) => date instanceof Date)
    }),
})

type FormData = yup.InferType<typeof schema>

function generateGoogleCalendarUrl(
  title: string,
  startDate: Date,
  endDate: Date,
): string {
  const formatDate = (d: Date) => d.toISOString().replace(/-|:|\.\d{3}/g, '')
  const dates = `${formatDate(startDate)}/${formatDate(addDays(endDate, 1))}`
  const details = encodeURIComponent(
    `Meal plan generated by Weekly Meal Planner`,
  )
  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(title)}&dates=${dates}&details=${details}`
}

function generateMicrosoftCalendarUrl(
  title: string,
  startDate: Date,
  endDate: Date,
): string {
  const formatDate = (d: Date) => d.toISOString().replace(/-|:|\.\d{3}/g, '')
  const params = new URLSearchParams({
    subject: title,
    startdt: formatDate(startDate),
    enddt: formatDate(addDays(endDate, 1)),
    body: 'Meal plan generated by Weekly Meal Planner',
    allday: 'true',
  })
  return `https://outlook.live.com/calendar/0/deeplink/compose?${params.toString()}`
}

function generateAppleCalendarUrl(
  title: string,
  startDate: Date,
  endDate: Date,
): string {
  const formatDate = (d: Date) => {
    return d
      .toISOString()
      .replace(/-|:|\.\d{3}/g, '')
      .slice(0, -1)
  }
  const dtstart = formatDate(startDate)
  const dtend = formatDate(addDays(endDate, 1))
  const description = 'Meal plan generated by Weekly Meal Planner'

  const icsContent = `BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
DTSTART;VALUE=DATE:${dtstart}
DTEND;VALUE=DATE:${dtend}
SUMMARY:${title}
DESCRIPTION:${description}
END:VEVENT
END:VCALENDAR`

  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' })
  return URL.createObjectURL(blob)
}

const calendarApps = [
  {
    id: 'google',
    name: 'Google Calendar',
    icon: (
      <svg viewBox="0 0 24 24" className="w-5 h-5" fill="currentColor">
        <path d="M21.3333 10.6667H12.8V14.9333H17.0667V21.3333H21.3333V10.6667ZM3.2 12.8H7.46667V21.3333H3.2V12.8ZM3.2 3.2H7.46667V7.46667H3.2V3.2ZM12.8 3.2H17.0667V7.46667H12.8V3.2ZM21.3333 3.2V7.46667H17.0667V3.2H21.3333Z" />
      </svg>
    ),
    color: 'hover:bg-red-500/10 hover:text-red-500',
    generateUrl: generateGoogleCalendarUrl,
  },
  {
    id: 'microsoft',
    name: 'Microsoft Calendar',
    icon: (
      <svg viewBox="0 0 24 24" className="w-5 h-5" fill="currentColor">
        <path d="M3 3h7v7H3V3zm0 11h7v7H3v-7zm11-11h7v7h-7V3zm0 11h7v7h-7v-7z" />
      </svg>
    ),
    color: 'hover:bg-blue-500/10 hover:text-blue-500',
    generateUrl: generateMicrosoftCalendarUrl,
  },
  {
    id: 'apple',
    name: 'Apple Calendar',
    icon: (
      <svg viewBox="0 0 24 24" className="w-5 h-5" fill="currentColor">
        <path d="M19 3h-1V1h-2v2H8V1H6v2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V8h14v11z" />
      </svg>
    ),
    color: 'hover:bg-gray-500/10 hover:text-gray-500',
    generateUrl: generateAppleCalendarUrl,
  },
  {
    id: 'outlook',
    name: 'Outlook',
    icon: (
      <svg viewBox="0 0 24 24" className="w-5 h-5" fill="currentColor">
        <path d="M20 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 14H4V8l8 5 8-5v10zm-8-7L4 6h16l-8 5z" />
      </svg>
    ),
    color: 'hover:bg-blue-500/10 hover:text-blue-500',
    generateUrl: generateMicrosoftCalendarUrl,
  },
]

export function SavePlanModal({
  isOpen,
  onClose,
  onSave,
  isSaving = false,
  mode = 'WEEK',
  selectedDay = null,
  mealPlanTitle = 'My Meal Plan',
}: SavePlanModalProps) {
  const [step, setStep] = useState(1)
  const [addToCalendar, setAddToCalendar] = useState(false)

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
    reset,
  } = useForm<FormData>({
    // @ts-expect-error
    resolver: yupResolver(schema),
    defaultValues: {
      planName: '',
      dateInput: undefined,
    },
  })

  const planName = watch('planName')
  const dateInput = watch('dateInput')

  const isDateSelected =
    mode === 'WEEK'
      ? dateInput &&
        !(dateInput instanceof Date) &&
        dateInput?.from &&
        dateInput?.to
      : dateInput instanceof Date

  const handleClose = () => {
    setStep(1)
    setAddToCalendar(false)
    reset()
    onClose()
  }

  const handleNext = () => {
    if (step === 1) {
      setStep(2)
    }
  }

  const handleBack = () => {
    if (step === 2) {
      setStep(1)
    }
  }

  const onSubmit: SubmitHandler<FormData> = async (data: FormData) => {
    try {
      await onSave(data.planName, data.dateInput!)
    } finally {
      handleClose()
    }
  }

  const handleCalendarAppClick = (app: (typeof calendarApps)[0]) => {
    if (!dateInput) return

    let startDate: Date
    let endDate: Date

    if (dateInput instanceof Date) {
      startDate = dateInput
      endDate = dateInput
    } else {
      startDate = dateInput.from!
      endDate = dateInput.to!
    }

    const title = planName || mealPlanTitle
    const url = app.generateUrl(title, startDate, endDate)

    if (app.id === 'apple') {
      const link = document.createElement('a')
      link.href = url
      link.download = `${title.replace(/\s+/g, '_')}.ics`
      link.click()
      URL.revokeObjectURL(url)
    } else {
      window.open(url, '_blank')
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-[425px]">
        {/** @ts-expect-error */}
        <form onSubmit={handleSubmit(onSubmit)}>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Save className="w-5 h-5" />
              {step === 1 ? 'Save Meal Plan' : 'Add to Calendar'}
            </DialogTitle>
            <DialogDescription>
              {step === 1
                ? 'Give your meal plan a name and select the schedule days.'
                : 'Choose a calendar app to add your meal plan.'}
            </DialogDescription>
          </DialogHeader>

          {step === 1 && (
            <div className="grid gap-4 py-4">
              <div className="grid gap-2">
                <Label htmlFor="plan-name">
                  Plan Name <span className="text-destructive">*</span>
                </Label>
                <Input
                  id="plan-name"
                  placeholder="e.g., Week 1 - Healthy Start"
                  {...register('planName')}
                />
                {errors.planName && (
                  <p className="text-sm text-destructive">
                    {errors.planName.message}
                  </p>
                )}
              </div>

              <div className="grid gap-2">
                <Label className="flex items-center gap-2">
                  Schedule day(s) <span className="text-destructive">*</span>
                </Label>
                {mode === 'WEEK' && !(dateInput instanceof Date) ? (
                  <>
                    <DatePickerWithRange
                      date={dateInput}
                      onDateChange={(date) => setValue('dateInput', date)}
                      className={errors.dateInput ? 'border-destructive' : ''}
                    />
                    {errors.dateInput && (
                      <p className="text-sm text-destructive">
                        {errors.dateInput.message as string}
                      </p>
                    )}
                    {dateInput?.from && dateInput?.to && (
                      <p className="text-sm text-muted-foreground">
                        Selected: {format(dateInput.from, 'MMM d, yyyy')} -{' '}
                        {format(dateInput.to, 'MMM d, yyyy')}
                      </p>
                    )}
                  </>
                ) : (
                  <>
                    <DatePicker
                      date={dateInput as Date}
                      onDateChange={(date) => setValue('dateInput', date)}
                      className={errors.dateInput ? 'border-destructive' : ''}
                    />
                    {errors.dateInput && (
                      <p className="text-sm text-destructive">
                        {errors.dateInput.message as string}
                      </p>
                    )}
                    {dateInput && (
                      <p className="text-sm text-muted-foreground">
                        Selected: {format(dateInput as Date, 'MMM d, yyyy')}
                      </p>
                    )}
                  </>
                )}
              </div>
            </div>
          )}

          {step === 2 && (
            <div className="grid gap-4 py-4">
              <div className="flex items-center gap-2">
                <Checkbox
                  id="add-to-calendar"
                  checked={addToCalendar}
                  onCheckedChange={(checked) =>
                    setAddToCalendar(checked as boolean)
                  }
                />
                <Label
                  htmlFor="add-to-calendar"
                  className="text-sm font-normal cursor-pointer"
                >
                  Add to calendar
                </Label>
              </div>

              <div className="grid gap-2">
                <Label className="text-xs text-muted-foreground">
                  Choose calendar app
                </Label>
                <div className="flex flex-wrap gap-2">
                  {calendarApps.map((app) => (
                    <Button
                      key={app.id}
                      type="button"
                      variant="outline"
                      size="sm"
                      className={cn(
                        'gap-2',
                        app.color,
                        !addToCalendar &&
                          isDateSelected &&
                          'opacity-50 cursor-not-allowed',
                      )}
                      disabled={!addToCalendar || !isDateSelected}
                      onClick={() => handleCalendarAppClick(app)}
                    >
                      {app.icon}
                      {app.name}
                    </Button>
                  ))}
                </div>
              </div>
            </div>
          )}

          <DialogFooter className="border-t pt-4 mt-4">
            {step === 1 ? (
              <>
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleClose}
                  disabled={isSaving}
                >
                  Cancel
                </Button>
                <Button type="button" onClick={handleNext}>
                  Next <ChevronRight className="w-4 h-4 ml-1" />
                </Button>
              </>
            ) : (
              <>
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleBack}
                  disabled={isSaving}
                >
                  <ChevronLeft className="w-4 h-4 mr-1" /> Back
                </Button>
                <Button type="submit" disabled={isSaving}>
                  {isSaving ? 'Saving...' : 'Save Plan'}
                </Button>
              </>
            )}
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
